
ingredient1 = input("Pick something for a salad.")
ounces1 = float(input("How many ounces of this ingredient?"))
ingredient2 = input("Pick another thing for the salad.")
ounces2 = float(input("How many ounces of this ingredient?"))
ingredient3 = input("Pick one final thing for the salad.")
ounces3 = float(input("How many ounces of this ingredient?"))
servings = int(input("How many servings of the salad?"))
print(f"You have {ounces2*servings: .2f} ounces of{ingredient2}")
print(f"You have {ounces1*servings: .2f} ounces of{ingredient1}")
print(f"You have {ounces3*servings: .2f} ounces of{ingredient3}")
